
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 04 13:29:15 CST 2016
//----------------------------------------------------

package automata;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACTIVA = 7;
  public static final int AVANZA = 4;
  public static final int NUMBER = 11;
  public static final int INICIO = 3;
  public static final int SEMI = 2;
  public static final int FIN = 8;
  public static final int EOF = 0;
  public static final int GIZQUIERDA = 6;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int GDERECHA = 5;
  public static final int LPAREN = 9;
}

